version: '3.4'
services:
  price-monitor:
    image: fy1128/price-monitor:latest
    volumes:
      - ./CONFIG.py:/usr/src/app/PriceMonitor/CONFIG.py
      - ./db.db:/usr/src/app/db_demo.db
    environment:
      - TYPE=js
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
       condition: on-failure
       max_attempts: 3
